=== lotods/umamusu-translate/src/data/internal/global.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "version": {
        "type": "integer",
        "maximum": 99
    },
      "bundle": {
        "type": "string",
        "minLength": 32,
        "maxLength": 32,
        "pattern": "^[0-9A-Z]{32}$"
      },
      "type": {
        "type": "string",
        "enum": ["story", "home", "race", "lyrics", "preview"]
      },
      "storyId": {
        "type": "string",
        "minLength": 4,
        "maxLength": 9,
        "pattern": "^[0-9]{4,9}$"
      },
      "title": {
        "type": "string",
        "minLength": 0
      },
      "lineLength": {"type": "integer"},
      "text": {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
              "jpName": {"type": "string"},
              "enName": {"type": "string"},
              "jpText": {"type": "string"},
              "enText": {"type": "string"},
              "nextBlock": {"type": "integer"},
              "origClipLength": {"type": "integer"},
              "pathId": {"type": "integer"},
              "blockIdx": {"type": "integer"},
              "time": {"type": "string"},
              "skip": {"type": "boolean"},
              "animData": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                      "origLen": {"type": "integer"},
                      "pathId": {"type": "integer"}
                    },
                    "required": [
                      "origLen",
                      "pathId"
                    ]
                  }
              }
            },
            "required": [
              "jpText",
              "enText"
             ]
          }
      },
      "modified": {
        "type": "integer",
        "format": "date-time"
      }
    },
    "required": [
      "version",
      "bundle",
      "type",
      "text"
    ]
  }

=== lotods/umamusu-translate/translations/story/50/1011/601 (今度こそ！).json
{
    "version": 5,
    "bundle": "LYB5DMAS72ZYJS5WNUISOHFBKEYNZWZE",
    "type": "story",
    "storyId": "501011601",
    "title": "今度こそ！",
    "text": [
        {
            "jpName": "グラスワンダー",
            "enName": "Grass Wonder",
            "jpText": "――前回のレースの結果から、\r\n反省すべき点がたくさん見つかりました。",
            "enText": "―The results of the last race revealed many \nthings that we need to reflect on.",
            "nextBlock": 2,
            "origClipLength": 67,
            "animData": [
                {
                    "origLen": 78,
                    "pathId": 4546386218738003005
                },
                {
                    "origLen": 78,
                    "pathId": 746444265557791198
                }
            ],
            "pathId": -6289563188953209971,
            "blockIdx": 1
        },
        {
            "jpName": "グラスワンダー",
            "enName": "Grass Wonder",
            "jpText": "そのおかげで、限られた時間の中で\r\n十全の努力をなせたつもりです。",
            "enText": "Thanks to this, I was able to make my best \nefforts within the limited time available.",
            "nextBlock": 3,
            "origClipLength": 66,
            "animData": [
                {
                    "origLen": 26,
                    "pathId": -8747274020489749791
                },
                {
                    "origLen": 77,
                    "pathId": -6769404137491786885
                }
            ],
            "pathId": 1090152928720906591,
            "blockIdx": 2
        },
        {
            "jpName": "グラスワンダー",
            "enName": "Grass Wonder",
            "jpText": "……2度と、\r\nあんな思いを味わわないために。",
            "enText": "……2 so I don't have to go through that again.",
            "nextBlock": 4,
            "origClipLength": 60,
            "choices": [
                {
                    "jpText": "今度こそ勝とう！",
                    "enText": "Let's win this time!",
                    "nextBlock": 4
                }
            ],
            "animData": [
                {
                    "origLen": 71,
                    "pathId": 6792010062937275714
                },
                {
                    "origLen": 71,
                    "pathId": -4335334627746763892
                }
            ],
            "pathId": -6645135575759986520,
            "blockIdx": 3
        },
        {
            "jpName": "グラスワンダー",
            "enName": "Grass Wonder",
            "jpText": "ふふ、次こそは後悔のない\r\n最高の結果を持ち帰って参りますね♪",
            "enText": "Next time, I will bring back the best result \nwith no regrets.",
            "nextBlock": -1,
            "origClipLength": 65,
            "animData": [
                {
                    "origLen": 71,
                    "pathId": 5747755029395933209
                },
                {
                    "origLen": 49,
                    "pathId": 1989586093009178966
                },
                {
                    "origLen": 76,
                    "pathId": -8420573964691730515
                }
            ],
            "pathId": 3508571825269540409,
            "blockIdx": 4
        }
    ],
    "modified": 1657555055
}

=== lotods/umamusu-translate/translations/story/50/1028/402 (甘くて小さいヒーロー).json
{
    "version": 5,
    "bundle": "MAW66B6IRIJKCDNE7RPY5KDLRT3JBXZN",
    "type": "story",
    "storyId": "501028402",
    "title": "甘くて小さいヒーロー",
    "text": [
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "ある日、ヒシアケボノからビコーペガサスの\n元気がないという話を聞く。\nどうやら原因はレース関係らしい。",
            "enText": "One day, I hear from Hsiakebono that Vicor \nPegasus is not doing well. Apparently, the \ncause is race-related.",
            "nextBlock": 2,
            "origClipLength": 111,
            "animData": [
                {
                    "origLen": 122,
                    "pathId": 3708366808352474611
                },
                {
                    "origLen": 122,
                    "pathId": 3092134722352959561
                },
                {
                    "origLen": 122,
                    "pathId": -2929648762332123495
                }
            ],
            "pathId": 4571590786691990171,
            "blockIdx": 1
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "とりあえず、まずは気分転換に連れ出そうと、\nミカン狩りへ行くことに。",
            "enText": "First of all, I decided to take her out for a \nchange of pace, and we went tangerine picking.",
            "nextBlock": 3,
            "origClipLength": 89,
            "animData": [
                {
                    "origLen": 16,
                    "pathId": 6168824813536112267
                },
                {
                    "origLen": 16,
                    "pathId": 8866801880411864131
                },
                {
                    "origLen": 16,
                    "pathId": 7420043907286595771
                },
                {
                    "origLen": 129,
                    "pathId": -2965014688697449602
                },
                {
                    "origLen": 130,
                    "pathId": -4968385447922855741
                },
                {
                    "origLen": 131,
                    "pathId": 3560563274227095604
                },
                {
                    "origLen": 131,
                    "pathId": 2833954237056794821
                },
                {
                    "origLen": 131,
                    "pathId": -1429275503304308417
                },
                {
                    "origLen": 132,
                    "pathId": -2537879602637921864
                }
            ],
            "pathId": -2781554502256518462,
            "blockIdx": 2
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "事件が発生するも、ビコーペガサスの勇気と\n諦めない心で無事解決。そんな姿を\n眩しそうに見るヒシアケボノ。",
            "enText": "The incident is solved with the courage \nof Vicor Pegasus and her never-giving-up \nspirit. The dazzling sight of Hsiayakebono \nlooks dazzled.",
            "nextBlock": 4,
            "origClipLength": 112,
            "animData": [
                {
                    "origLen": 129,
                    "pathId": 7210498465473910192
                },
                {
                    "origLen": 130,
                    "pathId": -5015055314072664824
                },
                {
                    "origLen": 131,
                    "pathId": -8387833008729347481
                },
                {
                    "origLen": 131,
                    "pathId": 2551834033388864574
                },
                {
                    "origLen": 131,
                    "pathId": -3062214280699166392
                },
                {
                    "origLen": 132,
                    "pathId": 1434879648933670221
                }
            ],
            "pathId": -8962713686873729237,
            "blockIdx": 3
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "――帰り道。小さな体を活かせず、レースで\n思うような成績が上げられず悩んでいた\nビコーペガサスをヒシアケボノは励ます。",
            "enText": "―The way back home. Biko Pegasus, who had \nbeen struggling to make the most of her small \nbody and achieve the desired results in the \nrace, was encouraged by Hsiarakebono. Biko \nPegasus, who was struggling to make the best \nuse of her small body and achieve the results \nshe wanted in the race.",
            "nextBlock": 5,
            "origClipLength": 121,
            "animData": [
                {
                    "origLen": 20,
                    "pathId": -245572575629269553
                },
                {
                    "origLen": 156,
                    "pathId": 7320067043945065939
                },
                {
                    "origLen": 174,
                    "pathId": 2009340286391692569
                },
                {
                    "origLen": 20,
                    "pathId": -5049141698609956602
                },
                {
                    "origLen": 157,
                    "pathId": 1190369466051205175
                },
                {
                    "origLen": 173,
                    "pathId": -7051575922404001490
                }
            ],
            "pathId": -6929385502965145432,
            "blockIdx": 4
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "『いつも前向きなビコーちゃんは、あたしの\nヒーローなんだよ』そんな言葉に背を押され、\nビコーペガサスは再び立ち上がるのだった。",
            "enText": "With these words, Biko Pegasus stood up \nagain. Biko Pegasus stood up again.",
            "nextBlock": -1,
            "origClipLength": 127,
            "animData": [
                {
                    "origLen": 139,
                    "pathId": -4251424564174341366
                },
                {
                    "origLen": 138,
                    "pathId": -8890134569379999588
                },
                {
                    "origLen": 138,
                    "pathId": -4201980695496697234
                },
                {
                    "origLen": 141,
                    "pathId": 3170867922262730114
                }
            ],
            "pathId": -7400129282547720094,
            "blockIdx": 5
        }
    ],
    "modified": 1657258135
}

=== lotods/umamusu-translate/translations/story/50/1012/402 (アタシのタイマン、アンタのタイマン).json
{
    "version": 5,
    "bundle": "RDUCG3JXNRX63BS5X7JCQDPHMTU76HVL",
    "type": "story",
    "storyId": "501012402",
    "title": "アタシのタイマン、アンタのタイマン",
    "text": [
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "『桜花賞』に向けて全力のヒシアマゾン。\nトレーナーも彼女のために、\n様々な新トレーニングを考案する。",
            "enText": "Hsiamazon is giving her all in preparation \nfor the \"Sakurabana-sho\" (Cherry Blossom \nPrize). The trainer also devises various new \ntraining programs for her. various new \ntraining exercises for her.",
            "nextBlock": 2,
            "origClipLength": 110,
            "animData": [
                {
                    "origLen": 141,
                    "pathId": 7711118597000266196
                },
                {
                    "origLen": 205,
                    "pathId": -924304806950583593
                }
            ],
            "pathId": -7275502027871048540,
            "blockIdx": 1
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "二人三脚で励む、努力の日々……！\n結果、ヒシアマゾンは大幅な成長を遂げる。",
            "enText": "Working hard together, the two of them work \nhard together. ……! As a result, Hsiamazon \nachieves significant growth.",
            "nextBlock": 3,
            "origClipLength": 93,
            "animData": [
                {
                    "origLen": 17,
                    "pathId": 5027823711577922264
                },
                {
                    "origLen": 17,
                    "pathId": 1964886998194065450
                }
            ],
            "pathId": 9028379065331308028,
            "blockIdx": 2
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "ヒシアマゾンはトレーナーの本気を知り、\n相棒として深い信頼を寄せるようになる。\n『桜花賞』は、もうすぐだ――",
            "enText": "Hsiamazon learns of the trainer's seriousness \nand comes to trust her deeply as a partner. \nThe \"Cherry Blossom Prize\" is just around \nthe corner.",
            "nextBlock": -1,
            "origClipLength": 115,
            "animData": [
                {
                    "origLen": 162,
                    "pathId": -420511235751279727
                },
                {
                    "origLen": 205,
                    "pathId": -8649149990915941581
                }
            ],
            "pathId": -8946047570725815079,
            "blockIdx": 3
        }
    ],
    "modified": 1657229578
}

=== lotods/umamusu-translate/translations/story/50/1017/427 (菊花賞の後に・三冠達成).json
{
    "version": 5,
    "bundle": "I3B3SO3DC6IU5QJOTJZQLGQYI6CRCNAQ",
    "type": "story",
    "storyId": "501017427",
    "title": "菊花賞の後に・三冠達成",
    "text": [
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "三冠、達成。惜しみない歓声を噛み締め、\r\n三本の指を掲げるシンボリルドルフ。\n次は先達も走る『有馬記念』だ。",
            "enText": "The Triple Crown is accomplished. Symbol \nRudolph bites back the cheers of the crowd \nand raises three fingers. Next is the \"Arima \nKinen,\" a race that her predecessors will \nalso be running.",
            "nextBlock": 2,
            "origClipLength": 115,
            "coloredText": [
                {
                    "jpText": "有馬記念",
                    "enText": "Arima Kinen (horse racing)"
                }
            ],
            "animData": [
                {
                    "origLen": 170,
                    "pathId": 7939712356181207353
                },
                {
                    "origLen": 166,
                    "pathId": 2621336131261954843
                }
            ],
            "pathId": -2607337442083466450,
            "blockIdx": 1
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "強者の走りを見届けたナリタブライアンが\r\n控室にきた。ヒリついた会話の中――",
            "enText": "NARITABURIAN came to the anteroom after \nwitnessing the strongman's run. In the midst \nof the flinty conversation―",
            "nextBlock": 3,
            "origClipLength": 94,
            "animData": [
                {
                    "origLen": 140,
                    "pathId": 2870196324564670238
                },
                {
                    "origLen": 166,
                    "pathId": 5585900867347843207
                },
                {
                    "origLen": 145,
                    "pathId": 2080716060090527416
                },
                {
                    "origLen": 158,
                    "pathId": 6201990572391813633
                }
            ],
            "pathId": 3011200376984327506,
            "blockIdx": 2
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "あくまで生徒会を気にかける\r\nシンボリルドルフに、ナリタブライアンは\n鋭い指摘を投げかけるのだった。",
            "enText": "Symbol Rudolph, who was always concerned \nabout the student council, made a sharp point \nto Naritabu Naritabu Bryan made a sharp point \nto Symbolo Rudolph, who was only concerned \nabout the student council.",
            "nextBlock": -1,
            "origClipLength": 110,
            "animData": [
                {
                    "origLen": 140,
                    "pathId": 8849793913307410028
                },
                {
                    "origLen": 166,
                    "pathId": 3563612415257139833
                },
                {
                    "origLen": 145,
                    "pathId": 527895413135665031
                },
                {
                    "origLen": 158,
                    "pathId": -4670660801022647813
                }
            ],
            "pathId": -9072733299207836621,
            "blockIdx": 3
        }
    ],
    "modified": 1657239274
}

=== lotods/umamusu-translate/translations/story/50/1009/601.json
{
    "version": 5,
    "bundle": "536SYPSTN52RCODY56L67V3IB2O3ZIAV",
    "type": "story",
    "storyId": "501009601",
    "title": "",
    "text": [
        {
            "jpName": "ダイワスカーレット",
            "enName": "Daiwa Scarlet",
            "jpText": "……トレーナー、よく聞いて。",
            "enText": "Listen up…… trainers.",
            "nextBlock": 2,
            "origClipLength": 54,
            "animData": [
                {
                    "origLen": 65,
                    "pathId": 3278694027349216036
                },
                {
                    "origLen": 65,
                    "pathId": 8073903814650407656
                }
            ],
            "pathId": -502229206429322639,
            "blockIdx": 1
        },
        {
            "jpName": "ダイワスカーレット",
            "enName": "Daiwa Scarlet",
            "jpText": "この前のアタシの走りは、詰めが甘かった。\r\n悔しいけど、それを素直に認めるわ。",
            "enText": "The last time I ran, I didn't pack it in \nwell. It's frustrating, but I'll admit it.",
            "nextBlock": 3,
            "origClipLength": 70,
            "animData": [
                {
                    "origLen": 43,
                    "pathId": 7976757557707349477
                },
                {
                    "origLen": 81,
                    "pathId": -8087863667500565133
                }
            ],
            "pathId": -4357018756899544141,
            "blockIdx": 2
        },
        {
            "jpName": "ダイワスカーレット",
            "enName": "Daiwa Scarlet",
            "jpText": "だから今回のレースでは――\r\nもうあんな、情けない走りは絶対にしない。",
            "enText": "So in this race―I will never run that \npathetic again.",
            "nextBlock": 4,
            "origClipLength": 67,
            "choices": [
                {
                    "jpText": "1番の走りを見せてほしい",
                    "enText": "I want to see you run number one.",
                    "nextBlock": 4
                }
            ],
            "animData": [
                {
                    "origLen": 38,
                    "pathId": -8086987040871331096
                },
                {
                    "origLen": 78,
                    "pathId": 6027500413535092553
                }
            ],
            "pathId": -8753865330386818277,
            "blockIdx": 3
        },
        {
            "jpName": "ダイワスカーレット",
            "enName": "Daiwa Scarlet",
            "jpText": "ええ、見せてあげるわ。\r\n――アンタの期待を超えた走りをね！",
            "enText": "Yes, I'll show you. ―I'll show you… and I'll \nexceed your expectations!",
            "nextBlock": 5,
            "origClipLength": 64,
            "animData": [
                {
                    "origLen": 32,
                    "pathId": 7567118900602973444
                },
                {
                    "origLen": 75,
                    "pathId": -5338271693276525197
                }
            ],
            "pathId": -5125736996299703283,
            "blockIdx": 4
        },
        {
            "jpName": "ダイワスカーレット",
            "enName": "Daiwa Scarlet",
            "jpText": "1番はアタシよ！\r\n今度こそ……誰にも譲らないんだから！",
            "enText": "I'm number one! This time I'm \nnot giving up…… to anyone!",
            "nextBlock": -1,
            "origClipLength": 63,
            "animData": [
                {
                    "origLen": 12,
                    "pathId": 8223246093974014828
                },
                {
                    "origLen": 74,
                    "pathId": 2482652122981460751
                }
            ],
            "pathId": 7734643877648793051,
            "blockIdx": 5
        }
    ],
    "modified": 1657176601
}

=== lotods/umamusu-translate/translations/story/50/1074/406 (夏合宿（2年目）スタート！).json
{
    "version": 5,
    "bundle": "RVCZM3HEZE7QI2QWY62EJBBFDOPQVRHU",
    "type": "story",
    "storyId": "501074406",
    "title": "夏合宿（2年目）スタート！",
    "text": [
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "迎えた夏合宿。『菊花賞』に向け、\r\nまずはメジロブライトが行うべき\nトレーニング内容を話し合うことになった。",
            "enText": "The summer training camp has arrived. The \nfirst thing to be discussed was the training \nthat Mejiro Bright should do for \"Kikka-sho\" \n(Chrysanthemum Award). The first step was to \ndiscuss the training that Mejiro Bright \nshould do for the",
            "nextBlock": 2,
            "origClipLength": 115,
            "animData": [
                {
                    "origLen": 127,
                    "pathId": 8104093159799340308
                },
                {
                    "origLen": 127,
                    "pathId": 942965507609980515
                },
                {
                    "origLen": 127,
                    "pathId": 4063016222664221016
                },
                {
                    "origLen": 127,
                    "pathId": 8368963564214663057
                }
            ],
            "pathId": 8052006131560807970,
            "blockIdx": 1
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "目指すレースが長距離であるならば、\r\nコーチ役も長距離に適したウマ娘に\n頼るべきだろう――",
            "enText": "If the race they are aiming for is a \nlong distance race, they should rely \non horsegirl who are suited for long \ndistance races to act as coaches.",
            "nextBlock": 3,
            "origClipLength": 103,
            "animData": [
                {
                    "origLen": 115,
                    "pathId": -6927681935617138292
                },
                {
                    "origLen": 127,
                    "pathId": -6933737753001854529
                },
                {
                    "origLen": 127,
                    "pathId": -3367036031450981409
                },
                {
                    "origLen": 115,
                    "pathId": 4404394805573640236
                }
            ],
            "pathId": 2099583886497286893,
            "blockIdx": 2
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "新たな方針は決まり、\r\n熱い特訓の日々が幕を開けようとしていた。",
            "enText": "A new policy was set, and the days of intense \ntraining were about to begin.",
            "nextBlock": -1,
            "origClipLength": 86,
            "animData": [
                {
                    "origLen": 127,
                    "pathId": -4143436019951751923
                },
                {
                    "origLen": 127,
                    "pathId": -8846276243511408424
                },
                {
                    "origLen": 127,
                    "pathId": 55664195104714391
                },
                {
                    "origLen": 127,
                    "pathId": -4896683354805144524
                }
            ],
            "pathId": 5615442806090579743,
            "blockIdx": 3
        }
    ],
    "modified": 1657451733
}

=== lotods/umamusu-translate/translations/story/50/1012/416 (安田記念にむけて).json
{
    "version": 5,
    "bundle": "YG4JKR4TATKRTMTLC6LFENHICEMSJJSQ",
    "type": "story",
    "storyId": "501012416",
    "title": "安田記念にむけて",
    "text": [
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "『安田記念』当日、レース前の会見にて。\r\nヒシアマゾンは、強敵たちに打ち勝ち、\nさらに上を目指したい、と意気込みを語る。",
            "enText": "At the pre-race press conference on the day \nof the \"Yasuda Kinen. Hsiamazon said that she \nwas determined to overcome her strong \nopponents and She is determined to overcome \nher strong rivals and aim for a higher level \nof performance.",
            "nextBlock": 2,
            "origClipLength": 123,
            "animData": [
                {
                    "origLen": 149,
                    "pathId": 3846474456218864366
                },
                {
                    "origLen": 173,
                    "pathId": -7880657634567250407
                }
            ],
            "pathId": 4016736613323089469,
            "blockIdx": 1
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "“女傑”の言葉に、客席は大いに沸いていた！\n多くの期待を背負い、彼女はレースに臨む――",
            "enText": "The audience was excited to hear \nthe words of the \"lady of the race\"! \nWith many expectations on her shoulders, \nshe is ready to race…",
            "nextBlock": -1,
            "origClipLength": 101,
            "animData": [
                {
                    "origLen": 16,
                    "pathId": 1893784883336025974
                },
                {
                    "origLen": 16,
                    "pathId": -3832315364105612593
                }
            ],
            "pathId": 6266657687510995961,
            "blockIdx": 2
        }
    ],
    "modified": 1657229598
}

=== lotods/umamusu-translate/translations/story/50/1015/601 (今度こそ！).json
{
    "version": 5,
    "bundle": "IH7NODQLWGMKVYUYFED7622GVOVLPXHQ",
    "type": "story",
    "storyId": "501015601",
    "title": "今度こそ！",
    "text": [
        {
            "jpName": "テイエムオペラオー",
            "enName": "TM Opera O",
            "jpText": "聞こえるよ、トレーナー君。",
            "enText": "I hear you, trainer.",
            "nextBlock": 2,
            "origClipLength": 61,
            "animData": [
                {
                    "origLen": 73,
                    "pathId": -3551574998297706103
                },
                {
                    "origLen": 72,
                    "pathId": -1527988736085987913
                },
                {
                    "origLen": 72,
                    "pathId": -3850337836018057163
                }
            ],
            "pathId": -4689239931516517554,
            "blockIdx": 1
        },
        {
            "jpName": "テイエムオペラオー",
            "enName": "TM Opera O",
            "jpText": "スタンドで、ボクの活躍を願うファンの声。\nそして――",
            "enText": "The fans in the stands, wishing \nme well. And then―",
            "nextBlock": 3,
            "origClipLength": 78,
            "animData": [
                {
                    "origLen": 18,
                    "pathId": -3252314912006184741
                },
                {
                    "origLen": 89,
                    "pathId": 194968209304683769
                },
                {
                    "origLen": 89,
                    "pathId": -7679787796752535149
                }
            ],
            "pathId": 7680160109697772738,
            "blockIdx": 2
        },
        {
            "jpName": "テイエムオペラオー",
            "enName": "TM Opera O",
            "jpText": "ボクの勝利を、復活を待ち望む\n君の心の声がね……！",
            "enText": "Your hearts long for my victory and my \nresurrection. ……!",
            "nextBlock": 4,
            "origClipLength": 77,
            "choices": [
                {
                    "jpText": "全力で応えてこい！",
                    "enText": "Go answer them with everything you've got!",
                    "nextBlock": 4
                },
                {
                    "jpText": "全力で応えてきて！",
                    "enText": "Go answer them to the best of your ability!",
                    "nextBlock": 4
                }
            ],
            "animData": [
                {
                    "origLen": 30,
                    "pathId": 2545837406342944390
                },
                {
                    "origLen": 45,
                    "pathId": -6111942415752269918
                },
                {
                    "origLen": 88,
                    "pathId": 4307663651360301912
                }
            ],
            "pathId": 8375684522449986089,
            "blockIdx": 3
        },
        {
            "jpName": "テイエムオペラオー",
            "enName": "TM Opera O",
            "jpText": "“覇王”の誇りにかけて……必ず！",
            "enText": "I'm proud to be a \"High King\"…… I promise!",
            "nextBlock": -1,
            "origClipLength": 65,
            "animData": [
                {
                    "origLen": 71,
                    "pathId": 7722600944288991238
                },
                {
                    "origLen": 62,
                    "pathId": -2090733033129664265
                },
                {
                    "origLen": 76,
                    "pathId": -717412838111694130
                }
            ],
            "pathId": 4665420020854435307,
            "blockIdx": 4
        }
    ],
    "modified": 1657555056
}
