=== lotods/umamusu-translate/src/data/internal/global.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "version": {
        "type": "integer",
        "maximum": 99
    },
      "bundle": {
        "type": "string",
        "minLength": 32,
        "maxLength": 32,
        "pattern": "^[0-9A-Z]{32}$"
      },
      "type": {
        "type": "string",
        "enum": ["story", "home", "race", "lyrics", "preview"]
      },
      "storyId": {
        "type": "string",
        "minLength": 4,
        "maxLength": 9,
        "pattern": "^[0-9]{4,9}$"
      },
      "title": {
        "type": "string",
        "minLength": 0
      },
      "lineLength": {"type": "integer"},
      "text": {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
              "jpName": {"type": "string"},
              "enName": {"type": "string"},
              "jpText": {"type": "string"},
              "enText": {"type": "string"},
              "nextBlock": {"type": "integer"},
              "origClipLength": {"type": "integer"},
              "pathId": {"type": "integer"},
              "blockIdx": {"type": "integer"},
              "time": {"type": "string"},
              "skip": {"type": "boolean"},
              "animData": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                      "origLen": {"type": "integer"},
                      "pathId": {"type": "integer"}
                    },
                    "required": [
                      "origLen",
                      "pathId"
                    ]
                  }
              }
            },
            "required": [
              "jpText",
              "enText"
             ]
          }
      },
      "modified": {
        "type": "integer",
        "format": "date-time"
      }
    },
    "required": [
      "version",
      "bundle",
      "type",
      "text"
    ]
  }

=== lotods/umamusu-translate/translations/story/50/1058/701 (休息はバッチリ！).json
{
    "version": 5,
    "bundle": "MWYJD6YN62LGUSVHJVDBBUANI7HM7WKL",
    "type": "story",
    "storyId": "501058701",
    "title": "休息はバッチリ！",
    "text": [
        {
            "jpName": "メイショウドトウ",
            "enName": "Meisho Doto",
            "jpText": "ふんふふ～ん、ふんふんふ～ん♪",
            "enText": "",
            "nextBlock": 2,
            "origClipLength": 64,
            "choices": [
                {
                    "jpText": "おはよう、鼻歌なんて珍しいな",
                    "enText": "Good morning. It's rare to see you humming.",
                    "nextBlock": 2
                },
                {
                    "jpText": "おはよう、鼻歌なんて珍しいね",
                    "enText": "Good morning. It's rare to see you humming.",
                    "nextBlock": 2
                }
            ],
            "animData": [
                {
                    "origLen": 75,
                    "pathId": 814311182725601480
                },
                {
                    "origLen": 75,
                    "pathId": 6759172295809636665
                }
            ],
            "pathId": -5539600000126088082,
            "blockIdx": 1
        },
        {
            "jpName": "メイショウドトウ",
            "enName": "Meisho Doto",
            "jpText": "ひゃわあ！　ト、トレーナーさんっ！？\r\nこ、これはつい、思い出にひたってと\nいいますか……っ。",
            "enText": "Whoa! You're a trainer! This \nis just a memory…………………",
            "nextBlock": 3,
            "origClipLength": 106,
            "animData": [
                {
                    "origLen": 89,
                    "pathId": 1855889767338351109
                },
                {
                    "origLen": 117,
                    "pathId": 5823935504914990916
                }
            ],
            "pathId": 6540193564535086972,
            "blockIdx": 2
        },
        {
            "jpName": "メイショウドトウ",
            "enName": "Meisho Doto",
            "jpText": "……実は昨日、偶然オペラオーさんに\r\n公園でお会いしまして……。",
            "enText": "…… In fact, I happened to meet Ms. Opera O in \nthe park yesterday. ……",
            "nextBlock": 4,
            "origClipLength": 86,
            "animData": [
                {
                    "origLen": 65,
                    "pathId": 2594663870018364267
                },
                {
                    "origLen": 97,
                    "pathId": 2257028704557633867
                }
            ],
            "pathId": -6563221966065939716,
            "blockIdx": 3
        },
        {
            "jpName": "メイショウドトウ",
            "enName": "Meisho Doto",
            "jpText": "なんと『オペラ覇王降臨・5時間特別版』を\r\n拝見することができたんですぅ～！",
            "enText": "I was able to see the special 5-hour \nedition of \"The Opera: The Descent \nof the Supreme King\"!",
            "nextBlock": 5,
            "origClipLength": 94,
            "animData": [
                {
                    "origLen": 84,
                    "pathId": -1528036871318989381
                },
                {
                    "origLen": 105,
                    "pathId": -2783591916996311905
                }
            ],
            "pathId": -3564323587353403093,
            "blockIdx": 4
        },
        {
            "jpName": "メイショウドトウ",
            "enName": "Meisho Doto",
            "jpText": "あの歌声を思い出すと、勇気が湧いてきます。\r\n今日はきっとドジらず過ごせる気がします～。",
            "enText": "Remembering that singing voice gives me \ncourage. I feel sure I will be able to spend \ntoday without screwing up～.",
            "nextBlock": 6,
            "origClipLength": 102,
            "animData": [
                {
                    "origLen": 100,
                    "pathId": 7492855543852852265
                },
                {
                    "origLen": 113,
                    "pathId": -6879957884825248659
                }
            ],
            "pathId": -8937873596832220456,
            "blockIdx": 5
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "どうやら充実した休日を過ごせたようだ！",
            "enText": "Looks like you had a well-deserved holiday!",
            "nextBlock": -1,
            "origClipLength": 69,
            "animData": [
                {
                    "origLen": 80,
                    "pathId": 8878451300717687642
                },
                {
                    "origLen": 80,
                    "pathId": -3066090348296145876
                }
            ],
            "pathId": 5219849968501829555,
            "blockIdx": 6
        }
    ],
    "modified": 1657555062
}

=== lotods/umamusu-translate/translations/story/50/1011/201 (朝日杯FSにむけて).json
{
    "version": 5,
    "bundle": "PLA2HAWHQT2CFMJMSMUWSGRIHYK4U2FX",
    "type": "story",
    "storyId": "501011201",
    "title": "朝日杯FSにむけて",
    "text": [
        {
            "jpName": "",
            "enName": "",
            "jpText": "いよいよ、『朝日杯フューチュリティ\r\nステークス』の当日を迎えた。",
            "enText": "Finally, the day of the \"Asahi Cup Futurity \nStakes\" arrived.",
            "nextBlock": 2,
            "origClipLength": 66,
            "animData": [
                {
                    "origLen": 77,
                    "pathId": 1395284352140134953
                },
                {
                    "origLen": 77,
                    "pathId": -6083342176704964723
                }
            ],
            "pathId": 6992503393210401755,
            "blockIdx": 1
        },
        {
            "jpName": "グラスワンダー",
            "enName": "Grass Wonder",
            "jpText": "さすがＧⅠレースですね～。\r\nスタンドがファンの方でいっぱいです。",
            "enText": "This is indeed a G1 race! The stands are \nfilled with fans.",
            "nextBlock": 3,
            "origClipLength": 85,
            "coloredText": [
                {
                    "jpText": "ＧⅠ",
                    "enText": "GI"
                }
            ],
            "animData": [
                {
                    "origLen": 43,
                    "pathId": -8383135649213466162
                },
                {
                    "origLen": 97,
                    "pathId": -447772184707923331
                }
            ],
            "pathId": 2908955814671405194,
            "blockIdx": 2
        },
        {
            "jpName": "グラスワンダー",
            "enName": "Grass Wonder",
            "jpText": "……トレーナーさんの緊張もひとしお、\r\nといったところでしょうか？",
            "enText": "…… trainers are also nervous, I guess.",
            "nextBlock": 4,
            "origClipLength": 66,
            "choices": [
                {
                    "jpText": "だ、だな……！",
                    "enText": "Duh, right. ……!",
                    "nextBlock": 4
                },
                {
                    "jpText": "だ、だね……！",
                    "enText": "Right, right. ……!",
                    "nextBlock": 4
                }
            ],
            "animData": [
                {
                    "origLen": 77,
                    "pathId": 3456168790622810063
                },
                {
                    "origLen": 77,
                    "pathId": -941069731910697602
                }
            ],
            "pathId": 825803125820022464,
            "blockIdx": 3
        },
        {
            "jpName": "グラスワンダー",
            "enName": "Grass Wonder",
            "jpText": "ふふっ。では今日も、緊張のご担当は\r\nトレーナーさんにお任せいたします♪",
            "enText": "Hmmm. Well, I'll leave it to your trainer to \ntake charge of your nerves today… ♪",
            "nextBlock": 5,
            "origClipLength": 68,
            "animData": [
                {
                    "origLen": 36,
                    "pathId": -15577824076174277
                },
                {
                    "origLen": 79,
                    "pathId": -7493560286652981105
                }
            ],
            "pathId": 3968085068418723014,
            "blockIdx": 4
        },
        {
            "jpName": "グラスワンダー",
            "enName": "Grass Wonder",
            "jpText": "――本日挑むのは『朝日杯FS』という\r\nレースだけではありません。",
            "enText": "―Today's challenge is not only \nthe \"Asahi Cup FS\" race.",
            "nextBlock": 6,
            "origClipLength": 66,
            "animData": [
                {
                    "origLen": 57,
                    "pathId": 4020178858291820286
                },
                {
                    "origLen": 77,
                    "pathId": 5987215944251749512
                }
            ],
            "pathId": 4006667859258092712,
            "blockIdx": 5
        },
        {
            "jpName": "グラスワンダー",
            "enName": "Grass Wonder",
            "jpText": "今現在、客席の方々の頭に浮かんでいるのは\r\nマルゼンスキーさんの名でしかないでしょう。",
            "enText": "Right now, the only name that comes \nto mind for those in the audience \nis that of Ms. Marzenski.",
            "nextBlock": 7,
            "origClipLength": 73,
            "animData": [
                {
                    "origLen": 45,
                    "pathId": -1117533583950365703
                },
                {
                    "origLen": 84,
                    "pathId": 5479905466016058219
                }
            ],
            "pathId": -648305128747104075,
            "blockIdx": 6
        },
        {
            "jpName": "グラスワンダー",
            "enName": "Grass Wonder",
            "jpText": "だからこそ……挑んで参ります。",
            "enText": "That is why we will be challenging ……",
            "nextBlock": 8,
            "origClipLength": 54,
            "animData": [
                {
                    "origLen": 39,
                    "pathId": -2612181976729140664
                },
                {
                    "origLen": 65,
                    "pathId": 2651066228624647661
                }
            ],
            "pathId": 7183890855370276645,
            "blockIdx": 7
        },
        {
            "jpName": "グラスワンダー",
            "enName": "Grass Wonder",
            "jpText": "“二世”でも“後継”でもない、\r\n頂点へ至る者としての実力を――",
            "enText": "Not as a second generation, not as a \nsuccessor, but as someone who has the ability \nto reach the top.",
            "nextBlock": 9,
            "origClipLength": 65,
            "animData": [
                {
                    "origLen": 100,
                    "pathId": 1863297758535408260
                },
                {
                    "origLen": 76,
                    "pathId": 3899708239890508582
                },
                {
                    "origLen": 76,
                    "pathId": 6108328668189849848
                }
            ],
            "pathId": -1687164267986976318,
            "blockIdx": 8
        },
        {
            "jpName": "グラスワンダー",
            "enName": "Grass Wonder",
            "jpText": "必ず、お見せして参ります。",
            "enText": "We will certainly show you.",
            "nextBlock": -1,
            "origClipLength": 53,
            "animData": [
                {
                    "origLen": 20,
                    "pathId": 6090090521095949173
                },
                {
                    "origLen": 24,
                    "pathId": 1509645241932435553
                },
                {
                    "origLen": 64,
                    "pathId": -4075429591469755847
                }
            ],
            "pathId": 2203220493816634508,
            "blockIdx": 9
        }
    ],
    "modified": 1657555055
}

=== lotods/umamusu-translate/translations/story/40/0004/051 (クライマックス1戦目の後に).json
{
    "version": 5,
    "bundle": "CSR6D54C43GTYUP4SSUM5ZFHJQ7H7SP3",
    "type": "story",
    "storyId": "400004051",
    "title": "クライマックス1戦目の後に",
    "text": [
        {
            "jpName": "秋川理事長",
            "enName": "Chairwoman Akikawa",
            "jpText": "～～っ！　感激ッ！！",
            "enText": "～～I'm so excited! I'm so impressed!",
            "nextBlock": 2,
            "origClipLength": 58,
            "animData": [
                {
                    "origLen": 69,
                    "pathId": -8616101847079983695
                },
                {
                    "origLen": 69,
                    "pathId": 5015699077159876757
                },
                {
                    "origLen": 69,
                    "pathId": -1066456505505675049
                }
            ],
            "pathId": 5531939649992030776,
            "blockIdx": 1
        },
        {
            "jpName": "秋川理事長",
            "enName": "Chairwoman Akikawa",
            "jpText": "まさにクライマックスにふさわしい\r\n最高のレースだった！",
            "enText": "It was truly a climax to a great race!",
            "nextBlock": 3,
            "origClipLength": 81,
            "choices": [
                {
                    "jpText": "ありがとうございます！",
                    "enText": "Thank you!",
                    "nextBlock": 3
                }
            ],
            "animData": [
                {
                    "origLen": 55,
                    "pathId": 2636513667234621975
                },
                {
                    "origLen": 92,
                    "pathId": -6108901795530762839
                },
                {
                    "origLen": 19,
                    "pathId": 6279301499402065927
                }
            ],
            "pathId": -5873921036042329995,
            "blockIdx": 2
        },
        {
            "jpName": "秋川理事長",
            "enName": "Chairwoman Akikawa",
            "jpText": "しかしっ！\r\n『最強』までの道のりはまだまだ遠い！",
            "enText": "But! The road to the \"Strongest\" \nis still far from over!",
            "nextBlock": 4,
            "origClipLength": 77,
            "animData": [
                {
                    "origLen": 79,
                    "pathId": 7502409570593030010
                },
                {
                    "origLen": 88,
                    "pathId": 5473183753326042878
                }
            ],
            "pathId": 6530783465702827460,
            "blockIdx": 3
        },
        {
            "jpName": "秋川理事長",
            "enName": "Chairwoman Akikawa",
            "jpText": "だからこそ、激励ッ！！\r\n<chrname>の善戦を心から祈念ッ！！",
            "enText": "That's why I'm giving you a pep talk! Wishing \n<chrname> a good fight!",
            "nextBlock": 5,
            "origClipLength": 89,
            "animData": [
                {
                    "origLen": 89,
                    "pathId": 7515624410659239267
                },
                {
                    "origLen": 100,
                    "pathId": 3245581165300755558
                }
            ],
            "pathId": 7850324947990441082,
            "blockIdx": 4
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "そうだ、良くも悪くもあと2戦……\r\n気を抜かずにいかなければ！",
            "enText": "Yes, for better or worse, we have two more \nrounds…… We have to stay on our toes!",
            "nextBlock": -1,
            "origClipLength": 85,
            "animData": [
                {
                    "origLen": 94,
                    "pathId": 908182998969539867
                },
                {
                    "origLen": 96,
                    "pathId": -1208385177372487769
                }
            ],
            "pathId": -8437885924855296274,
            "blockIdx": 5
        },
        {
            "jpName": "秋川理事長",
            "enName": "Chairwoman Akikawa",
            "jpText": "まさにクライマックスにふさわしい\r\n最高のレースだった！",
            "enText": "It was truly a climax to a great race!",
            "nextBlock": 7,
            "origClipLength": 81,
            "animData": [
                {
                    "origLen": 55,
                    "pathId": 7751932979022951829
                },
                {
                    "origLen": 92,
                    "pathId": -3297822295200784698
                },
                {
                    "origLen": 19,
                    "pathId": -3338458470914950788
                }
            ],
            "pathId": 8606092412271626673,
            "blockIdx": 6
        },
        {
            "jpName": "秋川理事長",
            "enName": "Chairwoman Akikawa",
            "jpText": "そして――敬服ッ！\r\n<chrname>も、不屈の精神で\n次のレースを見据えているっ！",
            "enText": "And―salute! <chrname> is also looking ahead \nto the next race with fortitude!",
            "nextBlock": 8,
            "origClipLength": 101,
            "animData": [
                {
                    "origLen": 79,
                    "pathId": -2469335189918589274
                },
                {
                    "origLen": 158,
                    "pathId": -8892983084866765223
                }
            ],
            "pathId": 3013430070678587080,
            "blockIdx": 7
        },
        {
            "jpName": "秋川理事長",
            "enName": "Chairwoman Akikawa",
            "jpText": "『最強』までの道のりはまだまだ遠い！\r\nしかしっ！\n閉ざされているわけでは決してないっ！",
            "enText": "The road to \"Strongest\" is far from over! \nBut! It is by no means closed!",
            "nextBlock": 9,
            "origClipLength": 102,
            "animData": [
                {
                    "origLen": 89,
                    "pathId": -8283573384759075358
                },
                {
                    "origLen": 149,
                    "pathId": 7324725113989152769
                }
            ],
            "pathId": 974662983108896384,
            "blockIdx": 8
        },
        {
            "jpName": "秋川理事長",
            "enName": "Chairwoman Akikawa",
            "jpText": "だからこそ、激励ッ！！\r\n<chrname>の善戦を心から祈念ッ！！",
            "enText": "That's why I'm giving you a pep talk! Wishing \n<chrname> a good fight!",
            "nextBlock": 10,
            "origClipLength": 89,
            "choices": [
                {
                    "jpText": "ありがとうございます！",
                    "enText": "Thank you!",
                    "nextBlock": 10
                }
            ],
            "animData": [
                {
                    "origLen": 94,
                    "pathId": 2984003299056516479
                },
                {
                    "origLen": 143,
                    "pathId": 1781333523789051723
                }
            ],
            "pathId": -4081601850618321360,
            "blockIdx": 9
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "そうだ、良くも悪くもあと2戦……\r\nまだまだチャンスはある！",
            "enText": "Yes, for better or worse, we still have two \nmore rounds…… to go!",
            "nextBlock": -1,
            "origClipLength": 84,
            "animData": [
                {
                    "origLen": 115,
                    "pathId": 4874972301603302800
                },
                {
                    "origLen": 143,
                    "pathId": 3184688583913360391
                }
            ],
            "pathId": 2188131321916215303,
            "blockIdx": 10
        }
    ],
    "modified": 1657215689
}

=== lotods/umamusu-translate/translations/story/50/1069/424 (日本ダービーの後に・まだ蕾にて).json
{
    "version": 5,
    "bundle": "ND67ZWBD267YJVKKVLDVBMQMQF4DD2CB",
    "type": "story",
    "storyId": "501069424",
    "title": "日本ダービーの後に・まだ蕾にて",
    "text": [
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "約束のダービー。サクラチヨノオーは、\r\n勝利をつかむことはできなかった。\n敗北を噛みしめ、芝を叩く彼女。",
            "enText": "The promised Derby. Sakura Chiono O was \nunable to seize victory. She bites her defeat \nand hits the turf.",
            "nextBlock": 2,
            "origClipLength": 112,
            "animData": [
                {
                    "origLen": 135,
                    "pathId": -7720678340161322696
                },
                {
                    "origLen": 145,
                    "pathId": -5158769585548809702
                }
            ],
            "pathId": -4477088867669827219,
            "blockIdx": 1
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "だが、彼女には『強くなってマルゼンスキー\r\nと走る』という目標もまだ残っていたはずだ。\nサクラチヨノオーは涙を拭いて立ち上がる。",
            "enText": "However, she must have still had the goal of \n\"getting stronger and running with Marzenski. \nSakura Chiono wiped her tears and stood up.",
            "nextBlock": 3,
            "origClipLength": 128,
            "animData": [
                {
                    "origLen": 149,
                    "pathId": -6204123331549031964
                },
                {
                    "origLen": 151,
                    "pathId": -4247134792413071241
                }
            ],
            "pathId": -217840447963524281,
            "blockIdx": 2
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "そんな彼女を見てマルゼンスキーは\r\n“最後の約束”を果たそう、\nと1人満足げに微笑むのだった。",
            "enText": "Seeing her like this, Marzenski \nsmiled with satisfaction as she \nfulfilled her \"last promise.",
            "nextBlock": 4,
            "origClipLength": 106,
            "animData": [
                {
                    "origLen": 14,
                    "pathId": -4552908955822550668
                },
                {
                    "origLen": 14,
                    "pathId": 8819855481089274633
                },
                {
                    "origLen": 190,
                    "pathId": -4224305411506359066
                },
                {
                    "origLen": 146,
                    "pathId": 5743798994123020759
                }
            ],
            "pathId": 6435618940051911541,
            "blockIdx": 3
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "ライバルとの勝負はサクラチヨノオーの\r\n成長や新たな力として繋がった。これからも\n彼女たちと走り続けたいと願う彼女。だが――",
            "enText": "The competition with rivals led to Sakura \nChiono's growth and new strength. From now on \nShe hopes to continue running with them in \nthe future. But…",
            "nextBlock": 5,
            "origClipLength": 125,
            "animData": [
                {
                    "origLen": 171,
                    "pathId": 2401779128902690228
                },
                {
                    "origLen": 191,
                    "pathId": 1959459480261929904
                },
                {
                    "origLen": 14,
                    "pathId": -2607148146199269853
                },
                {
                    "origLen": 14,
                    "pathId": -5496698880358735083
                }
            ],
            "pathId": -999293312596509521,
            "blockIdx": 4
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "その1人であったメジロアルダンが\r\n倒れてしまう。彼女の脚は今までの無理が\n影響し、非常に脆くなっていたのだ。",
            "enText": "One of them, Mejiro Aldan, collapses. \nHer legs had become very fragile \nher legs had become very fragile \nfrom the strain she had been",
            "nextBlock": 6,
            "origClipLength": 116,
            "animData": [
                {
                    "origLen": 172,
                    "pathId": 5338270294504577284
                },
                {
                    "origLen": 166,
                    "pathId": -4189510888081827862
                },
                {
                    "origLen": 163,
                    "pathId": 7748852082654018286
                },
                {
                    "origLen": 180,
                    "pathId": 967712375409070601
                },
                {
                    "origLen": 14,
                    "pathId": 4150487768279503141
                },
                {
                    "origLen": 14,
                    "pathId": -6609364630086864162
                }
            ],
            "pathId": 6316959044395729860,
            "blockIdx": 5
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "レースの世界を去ろうとする彼女。しかし、\r\nサクラチヨノオーはライバルである自分が\nその心を必ず引き留めさせると誓うのだった。",
            "enText": "She wants to leave the racing world. However, \nSakura Chiono O, her rival to make sure her \nheart stays with her.",
            "nextBlock": -1,
            "origClipLength": 127,
            "animData": [
                {
                    "origLen": 181,
                    "pathId": -6205836946047228896
                },
                {
                    "origLen": 166,
                    "pathId": 8682330407924772951
                },
                {
                    "origLen": 164,
                    "pathId": 314225305903609234
                },
                {
                    "origLen": 180,
                    "pathId": 7509846710334630326
                }
            ],
            "pathId": 1357952896926436789,
            "blockIdx": 6
        }
    ],
    "modified": 1657444073
}
