=== lotods/umamusu-translate/src/data/internal/global.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "version": {
        "type": "integer",
        "maximum": 99
    },
      "bundle": {
        "type": "string",
        "minLength": 32,
        "maxLength": 32,
        "pattern": "^[0-9A-Z]{32}$"
      },
      "type": {
        "type": "string",
        "enum": ["story", "home", "race", "lyrics", "preview"]
      },
      "storyId": {
        "type": "string",
        "minLength": 4,
        "maxLength": 9,
        "pattern": "^[0-9]{4,9}$"
      },
      "title": {
        "type": "string",
        "minLength": 0
      },
      "lineLength": {"type": "integer"},
      "text": {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
              "jpName": {"type": "string"},
              "enName": {"type": "string"},
              "jpText": {"type": "string"},
              "enText": {"type": "string"},
              "nextBlock": {"type": "integer"},
              "origClipLength": {"type": "integer"},
              "pathId": {"type": "integer"},
              "blockIdx": {"type": "integer"},
              "time": {"type": "string"},
              "skip": {"type": "boolean"},
              "animData": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                      "origLen": {"type": "integer"},
                      "pathId": {"type": "integer"}
                    },
                    "required": [
                      "origLen",
                      "pathId"
                    ]
                  }
              }
            },
            "required": [
              "jpText",
              "enText"
             ]
          }
      },
      "modified": {
        "type": "integer",
        "format": "date-time"
      }
    },
    "required": [
      "version",
      "bundle",
      "type",
      "text"
    ]
  }

=== lotods/umamusu-translate/translations/story/50/1039/730 (クレーンゲーム大成功！).json
{
    "version": 5,
    "bundle": "G4ZXL26G3KLNXNMDPQ7CKPHHLAORDTD4",
    "type": "story",
    "storyId": "501039730",
    "title": "クレーンゲーム大成功！",
    "text": [
        {
            "jpName": "カワカミプリンセス",
            "enName": "Kawakami Princess",
            "jpText": "すごい！　すごすぎですわっ！\r\nこんなにも爆盛りだなんて！",
            "enText": "That's amazing! This is too much! I can't \nbelieve it's such a big party!",
            "nextBlock": 2,
            "origClipLength": 82,
            "animData": [
                {
                    "origLen": 114,
                    "pathId": 2219669649008595230
                },
                {
                    "origLen": 93,
                    "pathId": -6112405689257286344
                },
                {
                    "origLen": 93,
                    "pathId": -2348556259174309717
                }
            ],
            "pathId": 4028246767024755467,
            "blockIdx": 1
        },
        {
            "jpName": "カワカミプリンセス",
            "enName": "Kawakami Princess",
            "jpText": "これだけあればトレーナー室に\r\nぬいぐるみ王国が作れちゃいますわね！",
            "enText": "With all this stuff, I could build a stuffed \nanimal kingdom in my trainer's office!",
            "nextBlock": 3,
            "origClipLength": 89,
            "choices": [
                {
                    "jpText": "賑やかになりそうだな",
                    "enText": "It's going to be lively.",
                    "nextBlock": 3
                },
                {
                    "jpText": "賑やかになりそうだね",
                    "enText": "It's going to be lively.",
                    "nextBlock": 3
                }
            ],
            "animData": [
                {
                    "origLen": 21,
                    "pathId": 6853592201786966324
                },
                {
                    "origLen": 100,
                    "pathId": 1647251435513990713
                },
                {
                    "origLen": 100,
                    "pathId": -8137497892195528148
                }
            ],
            "pathId": -3520235179924688018,
            "blockIdx": 2
        },
        {
            "jpName": "カワカミプリンセス",
            "enName": "Kawakami Princess",
            "jpText": "ふふっ、今日から私はぬいぐるみ王国の姫っ！",
            "enText": "From now on, I am the princess of the stuffed \nanimal kingdom!",
            "nextBlock": 4,
            "origClipLength": 72,
            "animData": [
                {
                    "origLen": 125,
                    "pathId": -7710232602651585910
                },
                {
                    "origLen": 83,
                    "pathId": 5547473534840833422
                },
                {
                    "origLen": 83,
                    "pathId": 6510679914546694282
                }
            ],
            "pathId": -4631291720976924415,
            "blockIdx": 3
        },
        {
            "jpName": "カワカミプリンセス",
            "enName": "Kawakami Princess",
            "jpText": "これからはこの子たちの応援も受けて\r\n姫、頑張っちゃいますわよ～！！",
            "enText": "From now on, with the support of these girls, \nPrincess, I will do my best～!",
            "nextBlock": 5,
            "origClipLength": 89,
            "animData": [
                {
                    "origLen": 125,
                    "pathId": 1709051156253672872
                },
                {
                    "origLen": 100,
                    "pathId": 5540119877124918457
                },
                {
                    "origLen": 100,
                    "pathId": 3048242641623568758
                }
            ],
            "pathId": 1695063150813977479,
            "blockIdx": 4
        },
        {
            "jpName": "",
            "enName": "",
            "jpText": "――大満足の結果だった！",
            "enText": "―I was very pleased with the results!",
            "nextBlock": -1,
            "origClipLength": 60,
            "animData": [
                {
                    "origLen": 20,
                    "pathId": 6405453273971546014
                },
                {
                    "origLen": 71,
                    "pathId": 3066995139809292951
                },
                {
                    "origLen": 71,
                    "pathId": -1307807067342350611
                }
            ],
            "pathId": -8459258910013980315,
            "blockIdx": 5
        }
    ],
    "modified": 1662157581
}

=== lotods/umamusu-translate/translations/story/50/1036/900 (自己紹介).json
{
    "version": 5,
    "bundle": "KFPPAOTHO7G7DK6J2UCCU3PN5WHT3GD5",
    "type": "story",
    "storyId": "501036900",
    "title": "自己紹介",
    "text": [
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "これから、トゥインクル・シリーズを\n担当ウマ娘と駆け抜ける日々が始まる。\nともに歩む彼女の名前は――",
            "enText": "From now on, the days of running through the \nTwinkle Series with the horsegirl in charge \nwill begin. Her name is…",
            "nextBlock": 2,
            "origClipLength": 110,
            "coloredText": [
                {
                    "jpText": "トゥインクル・シリーズ",
                    "enText": "Twinkle Series"
                }
            ],
            "pathId": 4292576588883909284,
            "blockIdx": 1
        },
        {
            "jpName": "エアシャカール",
            "enName": "Air Shakur",
            "jpText": "エアシャカールだ。言っとくが、\nアンタにはなにも期待してねェ。",
            "enText": "It's Air Shakur. I'm telling you, I don't \nexpect anything from you.",
            "nextBlock": 3,
            "origClipLength": 85,
            "coloredText": [
                {
                    "jpText": "エアシャカール",
                    "enText": "air shackard"
                }
            ],
            "animData": [
                {
                    "origLen": 70,
                    "pathId": -7966111817374665967
                },
                {
                    "origLen": 65,
                    "pathId": 547172218505453440
                }
            ],
            "pathId": -1755508489654882176,
            "blockIdx": 2
        },
        {
            "jpName": "エアシャカール",
            "enName": "Air Shakur",
            "jpText": "一応提案は聞いてやるが、決めるのはオレだ。\nそれをちゃんと理解しとけよ。",
            "enText": "I'll listen to your suggestions, \nbut I'm the one who decides. Make \nsure you understand that.",
            "nextBlock": 4,
            "origClipLength": 91,
            "animData": [
                {
                    "origLen": 49,
                    "pathId": -1888551283540368065
                },
                {
                    "origLen": 102,
                    "pathId": 6529779490063383436
                }
            ],
            "pathId": -6605248837441635521,
            "blockIdx": 3
        },
        {
            "jpName": "エアシャカール",
            "enName": "Air Shakur",
            "jpText": "もしオレの邪魔をしやがったら、\nそこでお前との契約はお終い。\nそれを肝に銘じておけ。",
            "enText": "If you interfere with me, your contract is \nover. Keep that in mind.",
            "nextBlock": 5,
            "origClipLength": 99,
            "animData": [
                {
                    "origLen": 62,
                    "pathId": -2295147762461878718
                },
                {
                    "origLen": 110,
                    "pathId": -7960160532304728451
                }
            ],
            "pathId": -2761957454676145649,
            "blockIdx": 4
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "こうして、<chrname>との\nトゥインクル・シリーズへの挑戦が\n始まったのだった！",
            "enText": "And so began <chrname>'s attempt at the \nTwinkle Series!",
            "nextBlock": -1,
            "origClipLength": 101,
            "animData": [
                {
                    "origLen": 112,
                    "pathId": 5529074286702042914
                },
                {
                    "origLen": 112,
                    "pathId": -6198183166847393668
                }
            ],
            "pathId": 2697453733545238257,
            "blockIdx": 5
        }
    ],
    "modified": 1657513099
}

=== lotods/umamusu-translate/translations/story/50/1062/415 (ダイヤモンドSにむけて).json
{
    "version": 5,
    "bundle": "COEVEYNKT2PV6Z6KQD3VYRG37TYAGZPP",
    "type": "story",
    "storyId": "501062415",
    "title": "ダイヤモンドSにむけて",
    "text": [
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "『ダイヤモンドS』当日。\r\nレース場前でファンに声をかけられたり――",
            "enText": "It was the day of the \"Diamond S.\" I was \napproached by fans in front of the \nracecourse. Fans called out to me in front of \nthe racecourse.",
            "nextBlock": 2,
            "origClipLength": 89,
            "animData": [
                {
                    "origLen": 133,
                    "pathId": -7595155336171077904
                },
                {
                    "origLen": 108,
                    "pathId": 5464112646464367785
                }
            ],
            "pathId": 8814345712670085359,
            "blockIdx": 1
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "以前、学内で出会った丸眼鏡の記者から、\r\n『タンホイザさんの言葉に救われた』\nと前向きに勝利を目指す姿を称賛されたり。",
            "enText": "A journalist with round glasses I once met on \ncampus said, \"Ms. Tanhiza's words saved my \nlife. and praised her positive attitude \ntoward winning.",
            "nextBlock": 3,
            "origClipLength": 121,
            "animData": [
                {
                    "origLen": 133,
                    "pathId": 1210372016199152166
                },
                {
                    "origLen": 146,
                    "pathId": 3332487374413828645
                }
            ],
            "pathId": 7422502810174240711,
            "blockIdx": 2
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "様々な人々から背中を押され挑む、\r\n『ダイヤモンドS』となった！",
            "enText": "With the support and encouragement \nof many people, I took on the challenge \nof the \"Diamond S\"!",
            "nextBlock": -1,
            "origClipLength": 86,
            "animData": [
                {
                    "origLen": 133,
                    "pathId": 1052394020724044920
                },
                {
                    "origLen": 108,
                    "pathId": 9205842838373441235
                }
            ],
            "pathId": 5320721876823262974,
            "blockIdx": 3
        }
    ],
    "modified": 1657434070
}

=== lotods/umamusu-translate/translations/story/50/1035/715 (追加の自主トレ).json
{
    "version": 5,
    "bundle": "UDIWVBRXGONMGSCH6TX2JQZBRLC6ZS43",
    "type": "story",
    "storyId": "501035715",
    "title": "追加の自主トレ",
    "text": [
        {
            "jpName": "",
            "enName": "",
            "jpText": "トレーニング終了後……。",
            "enText": "After the training is over, visit ……",
            "nextBlock": 2,
            "origClipLength": 60,
            "choices": [
                {
                    "jpText": "お疲れ様",
                    "enText": "that's enough for today",
                    "nextBlock": 2
                }
            ],
            "animData": [
                {
                    "origLen": 71,
                    "pathId": 4213486796393733132
                },
                {
                    "origLen": 71,
                    "pathId": 63537350753335207
                }
            ],
            "pathId": 8313873919088983720,
            "blockIdx": 1
        },
        {
            "jpName": "ウイニングチケット",
            "enName": "Winning Ticket",
            "jpText": "うんっ！　ありがとー！\r\nトレーナーさんもお疲れ様――",
            "enText": "Yeah! Thanks! Thanks to the trainer, too.",
            "nextBlock": 3,
            "origClipLength": 80,
            "animData": [
                {
                    "origLen": 62,
                    "pathId": 3137992636105322547
                },
                {
                    "origLen": 91,
                    "pathId": 923572932104656476
                }
            ],
            "pathId": 5482527780859948546,
            "blockIdx": 2
        },
        {
            "jpName": "ウイニングチケット",
            "enName": "Winning Ticket",
            "jpText": "って……んん？　あれあれっ……？\r\nアタシ、全力でトレーニングしてたのに――",
            "enText": "What is ……? What's that? ……? I was training \nas hard as I could…",
            "nextBlock": 4,
            "origClipLength": 94,
            "animData": [
                {
                    "origLen": 83,
                    "pathId": 930718956928105265
                },
                {
                    "origLen": 105,
                    "pathId": -7026038188314190150
                }
            ],
            "pathId": 1464108181668238148,
            "blockIdx": 3
        },
        {
            "jpName": "ウイニングチケット",
            "enName": "Winning Ticket",
            "jpText": "あんまり、お疲れ様じゃないぞーっ！？",
            "enText": "Not much, you're not tired!",
            "nextBlock": 5,
            "origClipLength": 68,
            "animData": [
                {
                    "origLen": 51,
                    "pathId": -528062574495464617
                },
                {
                    "origLen": 79,
                    "pathId": 3210602089625833673
                }
            ],
            "pathId": -4812944918155020735,
            "blockIdx": 4
        },
        {
            "jpName": "ウイニングチケット",
            "enName": "Winning Ticket",
            "jpText": "きっと、今日は調子がドッカーンなんだぁ！\r\nこれなら、まだまだトレーニングできるよ！",
            "enText": "I must be in smashing shape today! This means \nI can still train!",
            "nextBlock": 6,
            "origClipLength": 99,
            "animData": [
                {
                    "origLen": 62,
                    "pathId": -7348220353020911275
                },
                {
                    "origLen": 110,
                    "pathId": -6005253288102275068
                }
            ],
            "pathId": 4836842094210794471,
            "blockIdx": 5
        },
        {
            "jpName": "ウイニングチケット",
            "enName": "Winning Ticket",
            "jpText": "トレーナーさん！\r\nアタシ、自主トレしてくるねーっ！",
            "enText": "Trainer! I'm going to go train by myself!",
            "nextBlock": 7,
            "origClipLength": 78,
            "choices": [
                {
                    "jpText": "よし！やろう！",
                    "enText": "Let's do it! Let's do it!",
                    "nextBlock": 8
                },
                {
                    "jpText": "よし！やりましょう！",
                    "enText": "Let's do it! Let's do it!",
                    "nextBlock": 8
                },
                {
                    "jpText": "全力は後にとっておこう",
                    "enText": "Let's save our best for later.",
                    "nextBlock": 11
                }
            ],
            "animData": [
                {
                    "origLen": 51,
                    "pathId": 1040534060981930439
                },
                {
                    "origLen": 89,
                    "pathId": -2316574898388053774
                }
            ],
            "pathId": 7255902171096392673,
            "blockIdx": 6
        },
        {
            "jpName": "ウイニングチケット",
            "enName": "Winning Ticket",
            "jpText": "トレーナーさん！\r\nアタシ、自主トレしてくるねーっ！",
            "enText": "Trainer! I'm going to go train by myself!",
            "nextBlock": 8,
            "origClipLength": 78,
            "choices": [
                {
                    "jpText": "よし！やろう！",
                    "enText": "Let's do it! Let's do it!",
                    "nextBlock": 8
                },
                {
                    "jpText": "よし！やりましょう！",
                    "enText": "Let's do it! Let's do it!",
                    "nextBlock": 8
                },
                {
                    "jpText": "全力は後にとっておこう",
                    "enText": "Let's save our best for later.",
                    "nextBlock": 11
                }
            ],
            "animData": [
                {
                    "origLen": 51,
                    "pathId": -4989991977821928768
                },
                {
                    "origLen": 89,
                    "pathId": -2808232746616545145
                }
            ],
            "pathId": 6745875608843499083,
            "blockIdx": 7
        },
        {
            "jpName": "ウイニングチケット",
            "enName": "Winning Ticket",
            "jpText": "おーーーー！！\r\nがんばるぞーーーっ！！",
            "enText": "Ooooooooo!!! I'll do my best!!!!",
            "nextBlock": 9,
            "origClipLength": 71,
            "animData": [
                {
                    "origLen": 59,
                    "pathId": 1142617071378039624
                },
                {
                    "origLen": 82,
                    "pathId": 8285473278605269961
                }
            ],
            "pathId": -3963589911091468659,
            "blockIdx": 8
        },
        {
            "jpName": "ウイニングチケット",
            "enName": "Winning Ticket",
            "jpText": "まずは、トレーニングコースをダッシュだぁ！\r\n全力ッ！　全開ッ！　レッツゴーーーッ！！",
            "enText": "First, let's dash down the training course! \nFull power! Full throttle! Let's goooooo!",
            "nextBlock": 10,
            "origClipLength": 101,
            "animData": [
                {
                    "origLen": 90,
                    "pathId": -5662744877522246727
                },
                {
                    "origLen": 112,
                    "pathId": -2425434201005113480
                }
            ],
            "pathId": -6489306294504196582,
            "blockIdx": 9
        },
        {
            "jpName": "",
            "enName": "",
            "jpText": "ウイニングチケットと一緒に、\r\n追加トレー二ングを行った。",
            "enText": "Additional training was provided along with \nthe winning ticket.",
            "nextBlock": -1,
            "origClipLength": 82,
            "animData": [
                {
                    "origLen": 93,
                    "pathId": -1696958696005099216
                },
                {
                    "origLen": 93,
                    "pathId": -6140869840130997255
                }
            ],
            "pathId": 6761979206343056853,
            "blockIdx": 10
        },
        {
            "jpName": "ウイニングチケット",
            "enName": "Winning Ticket",
            "jpText": "ハッ……！？！？\r\nな、なるほどぉ～～～！！",
            "enText": "Ha……! I see～!",
            "nextBlock": 12,
            "origClipLength": 73,
            "animData": [
                {
                    "origLen": 80,
                    "pathId": 3314694876340284581
                },
                {
                    "origLen": 84,
                    "pathId": 7123061089242438883
                }
            ],
            "pathId": 915269409662755609,
            "blockIdx": 11
        },
        {
            "jpName": "ウイニングチケット",
            "enName": "Winning Ticket",
            "jpText": "全力をとっておけば、もっと全力が出せるッ！\r\nさっすがトレーナーさん！\n気づかなかったよ～！",
            "enText": "If you save all your energy, you \ncan give it more! Way to go, trainer! \nI didn't even notice～!",
            "nextBlock": 13,
            "origClipLength": 105,
            "animData": [
                {
                    "origLen": 68,
                    "pathId": 4261881595750705403
                },
                {
                    "origLen": 116,
                    "pathId": 5103706972930689509
                }
            ],
            "pathId": 1387221920523950662,
            "blockIdx": 12
        },
        {
            "jpName": "",
            "enName": "",
            "jpText": "今後のトレーニングのためにも、\r\nウイニングチケットを休ませた。",
            "enText": "I rested my winnings ticket \nfor future training.",
            "nextBlock": -1,
            "origClipLength": 86,
            "animData": [
                {
                    "origLen": 97,
                    "pathId": 8489120819920273950
                },
                {
                    "origLen": 97,
                    "pathId": -684677793348918940
                }
            ],
            "pathId": 1552056884808463238,
            "blockIdx": 13
        }
    ],
    "modified": 1657555059
}

=== lotods/umamusu-translate/translations/story/50/1013/731 (クレーンゲーム成功！).json
{
    "version": 5,
    "bundle": "37EWRL5AM6JYNHSLXK24EGSARXCVJTUS",
    "type": "story",
    "storyId": "501013731",
    "title": "クレーンゲーム成功！",
    "text": [
        {
            "jpName": "メジロマックイーン",
            "enName": "Mejiro McQueen",
            "jpText": "まあ……！　ありがとうございます！",
            "enText": "Well, ……! Thank you!",
            "nextBlock": 2,
            "origClipLength": 67,
            "animData": [
                {
                    "origLen": 79,
                    "pathId": -2150260599928452906
                },
                {
                    "origLen": 79,
                    "pathId": -7631918830594955418
                },
                {
                    "origLen": 89,
                    "pathId": -7242940428222355353
                }
            ],
            "pathId": 8232501724309812895,
            "blockIdx": 1
        },
        {
            "jpName": "メジロマックイーン",
            "enName": "Mejiro McQueen",
            "jpText": "細かいところまで作りこまれていて、\n間近で見ると、なお可愛いですわね！",
            "enText": "It's so detailed and pretty, and even \nprettier up close!",
            "nextBlock": 3,
            "origClipLength": 90,
            "animData": [
                {
                    "origLen": 30,
                    "pathId": 5052971794375843033
                },
                {
                    "origLen": 102,
                    "pathId": -1329902687061525039
                },
                {
                    "origLen": 102,
                    "pathId": -8476955235212646383
                }
            ],
            "pathId": -4449393503136395628,
            "blockIdx": 2
        },
        {
            "jpName": "メジロマックイーン",
            "enName": "Mejiro McQueen",
            "jpText": "ふふっ……大切にいたしますわ！",
            "enText": "Phew……… I will treasure it!",
            "nextBlock": 4,
            "origClipLength": 64,
            "animData": [
                {
                    "origLen": 68,
                    "pathId": -608459469946247953
                },
                {
                    "origLen": 79,
                    "pathId": -5537623933360562136
                },
                {
                    "origLen": 89,
                    "pathId": -2761863557381994984
                }
            ],
            "pathId": -2059797497510437973,
            "blockIdx": 3
        },
        {
            "jpName": "",
            "enName": "",
            "jpText": "――それなりの結果だった！",
            "enText": "―a reasonable result!",
            "nextBlock": -1,
            "origClipLength": 61,
            "animData": [
                {
                    "origLen": 73,
                    "pathId": 7593081140011772841
                },
                {
                    "origLen": 84,
                    "pathId": 6263423069622667568
                },
                {
                    "origLen": 93,
                    "pathId": -1450378246995502532
                }
            ],
            "pathId": 5866860618297645835,
            "blockIdx": 4
        }
    ],
    "modified": 1662157319
}

=== lotods/umamusu-translate/translations/story/50/1009/414 (日本ダービーにむけて).json
{
    "version": 5,
    "bundle": "GQT27ZXBC2SEOCMY7O6I6SVPFXJXEJDQ",
    "type": "story",
    "storyId": "501009414",
    "title": "日本ダービーにむけて",
    "text": [
        {
            "jpName": "",
            "enName": "",
            "jpText": "ウオッカの『日本ダービー』への熱い想いを\r\n偶然、耳にしたダイワスカーレットは――",
            "enText": "Daiwa Scarlet, who happened to overhear \nVodka's passion for the Japanese Derby, was…",
            "nextBlock": 2,
            "origClipLength": 71,
            "animData": [
                {
                    "origLen": 102,
                    "pathId": 7289108676144356465
                },
                {
                    "origLen": 89,
                    "pathId": -5922556831910359586
                }
            ],
            "pathId": -8027577165363802905,
            "blockIdx": 1
        },
        {
            "jpName": "",
            "enName": "",
            "jpText": "改めてウオッカに勝つこと、\r\n“1番”になることを心に決めるのだった。",
            "enText": "Once again, she made up her mind to beat \nVodka and become \"No. 1.",
            "nextBlock": -1,
            "origClipLength": 67,
            "animData": [
                {
                    "origLen": 102,
                    "pathId": 2754893890962648540
                },
                {
                    "origLen": 89,
                    "pathId": -3131894661826640559
                }
            ],
            "pathId": -3002596362406879117,
            "blockIdx": 2
        }
    ],
    "modified": 1657176600
}

=== lotods/umamusu-translate/translations/story/50/1037/404 (Die Chrysantheme).json
{
    "version": 5,
    "bundle": "JEXO5JRVUQTYLTVMEH55T7PUA3IK7TNY",
    "type": "story",
    "storyId": "501037404",
    "title": "Die Chrysantheme",
    "text": [
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "1度は外した目標である『菊花賞』。\n調整が間に合い、挑戦することになったが――",
            "enText": "The Kikka-sho\" was a goal that she had once \nmissed. She made adjustments in time and \ndecided to take on the challenge, but…",
            "nextBlock": 2,
            "origClipLength": 95,
            "animData": [
                {
                    "origLen": 106,
                    "pathId": -2150192329480930340
                },
                {
                    "origLen": 107,
                    "pathId": 5203401868464812243
                }
            ],
            "pathId": -5085673946109470975,
            "blockIdx": 1
        },
        {
            "jpName": "モノローグ",
            "enName": "",
            "jpText": "エイシンフラッシュは次の目標を見ている。\nたとえ『菊花賞』であろうと、\nいつも通り結果を出すだけだ。",
            "enText": "Eishin Flash is looking at her next target. \nEven if it's the Kikka-sho. She just has to \nachieve the result as usual.",
            "nextBlock": -1,
            "origClipLength": 110,
            "animData": [
                {
                    "origLen": 121,
                    "pathId": -6531801342538123093
                },
                {
                    "origLen": 123,
                    "pathId": 6901735817207052166
                }
            ],
            "pathId": 2253205709475117594,
            "blockIdx": 2
        }
    ],
    "modified": 1657448261
}
